### PR TITLE
simple function in head that clears all bootstrap modals when they ar…

### PR DESCRIPTION
**Pull request by umorenovanderlaanTechtonic**
…e closed

Apparently this is a known bootstrap issue. I just added a three line script in the head that refers to all bootstrap modals in the body to clear them when they are closed.

### CODE REVIEW

**Comment by jhernandezinzunzaTechtonic** [comment]
Cool, looks awesome.  For the rest of the changes it tries to show, is that just indentation fixes?

**Comment by umorenovanderlaanTechtonic** [comment]
Yep, all the other changes are just formatting. No content outside the head was harmed in the making of this pr.

**Comment by jhernandezinzunzaTechtonic** [comment]
even after a refresh :(

**Comment by umorenovanderlaanTechtonic** [comment]
Weirdly it works when adding a task, but not when closing the modal. it should trigger whenever the modal is hidden which is why I didn't dig into it any deeper, but that's not happening for whatever reason. sorry for the sloppy testing on my end D:

**Pull request merged**
